name: Geeqie x86_64 AppImage build
run-name: ${{ github.actor }} is running Geeqie x86_64 AppImage build
on: [push]
jobs:
  Build-AppImage:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:rolling

    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install -y appstream
          apt install -y build-essential
          apt install -y curl
          apt install -y docbook-xsl
          apt install -y evince
          apt install -y file
          apt install -y fop
          apt install -y fuse
          apt install -y gettext
          apt install -y git
          apt install -y libarchive-dev
          apt install -y libcfitsio-dev
          apt install -y libcfitsio-dev
          apt install -y libchamplain-0.12-dev
          apt install -y libchamplain-gtk-0.12-dev
          apt install -y libdjvulibre-dev
          apt install -y libdw-dev
          apt install -y libdwarf-dev
          apt install -y libffmpegthumbnailer-dev
          apt install -y libgexiv2-dev
          apt install -y libgspell-1-dev
          apt install -y libgtk-3-bin
          apt install -y libgtk-3-dev
          apt install -y libheif-dev
          apt install -y libimath-dev
          apt install -y libjxl-dev
          apt install -y liblua5.3-dev
          apt install -y libomp-dev
          apt install -y libopenexr-dev
          apt install -y libpoppler-glib-dev
          apt install -y libraw-dev
          apt install -y libunwind-dev
          apt install -y libwebp-dev
          apt install -y libwebp7
          apt install -y pandoc
          apt install -y patchelf
          apt install -y wget
          apt install -y xsltproc
          apt install -y yelp-tools

      - name: Checkout
        uses: actions/checkout@v4

      - name: Mark repo as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: git fetch
        run: |
          git fetch --tags --force
          git fetch --depth=1000000

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Meson build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
          setup-options: >
            --prefix=/usr
            --datadir=share
            -Dextended_stacktrace=disabled
          options: --verbose
          meson-version: 1.3.2

      - name: Ninja compile
        run: DESTDIR=${{ github.workspace }}/AppDir ninja -C build install

# The linuxdeploy-plugin-gtk forces the backend to be X11, as it was considered
# that Wayland has problems. Delete this and let the user choose.
      - name: Download linuxdeploy and plugin
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          wget https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh
          chmod +x linuxdeploy-plugin-gtk.sh
          sed -i '/GDK_BACKEND/d' linuxdeploy-plugin-gtk.sh

      - name: Extract linuxdeploy to avoid FUSE
        run: |
          chmod +x linuxdeploy-x86_64.AppImage
          ./linuxdeploy-x86_64.AppImage --appimage-extract
          mv squashfs-root linuxdeploy

      - name: Build AppImage
        run: |
          ./linuxdeploy/AppRun --appdir ${{ github.workspace }}/AppDir \
            --desktop-file ${{ github.workspace }}/AppDir/usr/share/applications/org.geeqie.Geeqie.desktop \
            --plugin gtk \
            --output appimage
          mv Geeqie-x86_64.AppImage Geeqie-latest-x86_64.AppImage

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
           allowUpdates: true
           tag: continuous
           name: Continuous build
           prerelease: true
           artifacts: "Geeqie-latest-x86_64.AppImage"

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs-all-build-appimage
          path: ${{ github.workspace }}/build/meson-logs/*.txt
          retention-days: 5
